<?php
/**
 * InlineObject273
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Fortigate\FortiOS
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FortiOS CMDB
 *
 * REST API for configuring FortiOS objects and settings
 *
 * The version of the OpenAPI document: v2
 * Contact: fosguiqateam@fortinet.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Fortigate\FortiOS\Model\CMDB;

use \ArrayAccess;
use \Fortigate\FortiOS\ObjectSerializer;

/**
 * InlineObject273 Class Doc Comment
 *
 * @category Class
 * @package  Fortigate\FortiOS
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class InlineObject273 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'inline_object_273';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'auto_install_config' => 'string',
        'auto_install_image' => 'string',
        'default_config_file' => 'string',
        'default_image_file' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'auto_install_config' => null,
        'auto_install_image' => null,
        'default_config_file' => null,
        'default_image_file' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'auto_install_config' => 'auto-install-config',
        'auto_install_image' => 'auto-install-image',
        'default_config_file' => 'default-config-file',
        'default_image_file' => 'default-image-file'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'auto_install_config' => 'setAutoInstallConfig',
        'auto_install_image' => 'setAutoInstallImage',
        'default_config_file' => 'setDefaultConfigFile',
        'default_image_file' => 'setDefaultImageFile'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'auto_install_config' => 'getAutoInstallConfig',
        'auto_install_image' => 'getAutoInstallImage',
        'default_config_file' => 'getDefaultConfigFile',
        'default_image_file' => 'getDefaultImageFile'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const AUTO_INSTALL_CONFIG_ENABLE = 'enable';
    const AUTO_INSTALL_CONFIG_DISABLE = 'disable';
    const AUTO_INSTALL_IMAGE_ENABLE = 'enable';
    const AUTO_INSTALL_IMAGE_DISABLE = 'disable';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAutoInstallConfigAllowableValues()
    {
        return [
            self::AUTO_INSTALL_CONFIG_ENABLE,
            self::AUTO_INSTALL_CONFIG_DISABLE,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAutoInstallImageAllowableValues()
    {
        return [
            self::AUTO_INSTALL_IMAGE_ENABLE,
            self::AUTO_INSTALL_IMAGE_DISABLE,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['auto_install_config'] = $data['auto_install_config'] ?? null;
        $this->container['auto_install_image'] = $data['auto_install_image'] ?? null;
        $this->container['default_config_file'] = $data['default_config_file'] ?? null;
        $this->container['default_image_file'] = $data['default_image_file'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getAutoInstallConfigAllowableValues();
        if (!is_null($this->container['auto_install_config']) && !in_array($this->container['auto_install_config'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'auto_install_config', must be one of '%s'",
                $this->container['auto_install_config'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getAutoInstallImageAllowableValues();
        if (!is_null($this->container['auto_install_image']) && !in_array($this->container['auto_install_image'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'auto_install_image', must be one of '%s'",
                $this->container['auto_install_image'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['default_config_file']) && (mb_strlen($this->container['default_config_file']) > 127)) {
            $invalidProperties[] = "invalid value for 'default_config_file', the character length must be smaller than or equal to 127.";
        }

        if (!is_null($this->container['default_image_file']) && (mb_strlen($this->container['default_image_file']) > 127)) {
            $invalidProperties[] = "invalid value for 'default_image_file', the character length must be smaller than or equal to 127.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets auto_install_config
     *
     * @return string|null
     */
    public function getAutoInstallConfig()
    {
        return $this->container['auto_install_config'];
    }

    /**
     * Sets auto_install_config
     *
     * @param string|null $auto_install_config Enable/disable auto install the config in USB disk.    enable:Enable config.    disable:Disable config.
     *
     * @return self
     */
    public function setAutoInstallConfig($auto_install_config)
    {
        $allowedValues = $this->getAutoInstallConfigAllowableValues();
        if (!is_null($auto_install_config) && !in_array($auto_install_config, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'auto_install_config', must be one of '%s'",
                    $auto_install_config,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['auto_install_config'] = $auto_install_config;

        return $this;
    }

    /**
     * Gets auto_install_image
     *
     * @return string|null
     */
    public function getAutoInstallImage()
    {
        return $this->container['auto_install_image'];
    }

    /**
     * Sets auto_install_image
     *
     * @param string|null $auto_install_image Enable/disable auto install the image in USB disk.    enable:Enable config.    disable:Disable config.
     *
     * @return self
     */
    public function setAutoInstallImage($auto_install_image)
    {
        $allowedValues = $this->getAutoInstallImageAllowableValues();
        if (!is_null($auto_install_image) && !in_array($auto_install_image, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'auto_install_image', must be one of '%s'",
                    $auto_install_image,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['auto_install_image'] = $auto_install_image;

        return $this;
    }

    /**
     * Gets default_config_file
     *
     * @return string|null
     */
    public function getDefaultConfigFile()
    {
        return $this->container['default_config_file'];
    }

    /**
     * Sets default_config_file
     *
     * @param string|null $default_config_file Default config file name in USB disk.
     *
     * @return self
     */
    public function setDefaultConfigFile($default_config_file)
    {
        if (!is_null($default_config_file) && (mb_strlen($default_config_file) > 127)) {
            throw new \InvalidArgumentException('invalid length for $default_config_file when calling InlineObject273., must be smaller than or equal to 127.');
        }

        $this->container['default_config_file'] = $default_config_file;

        return $this;
    }

    /**
     * Gets default_image_file
     *
     * @return string|null
     */
    public function getDefaultImageFile()
    {
        return $this->container['default_image_file'];
    }

    /**
     * Sets default_image_file
     *
     * @param string|null $default_image_file Default image file name in USB disk.
     *
     * @return self
     */
    public function setDefaultImageFile($default_image_file)
    {
        if (!is_null($default_image_file) && (mb_strlen($default_image_file) > 127)) {
            throw new \InvalidArgumentException('invalid length for $default_image_file when calling InlineObject273., must be smaller than or equal to 127.');
        }

        $this->container['default_image_file'] = $default_image_file;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


