<?php
/**
 * SwitchControllerManagedSwitchSwitchIdStpSettings
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Fortigate\FortiOS
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FortiOS CMDB
 *
 * REST API for configuring FortiOS objects and settings
 *
 * The version of the OpenAPI document: v2
 * Contact: fosguiqateam@fortinet.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Fortigate\FortiOS\Model\CMDB;

use \ArrayAccess;
use \Fortigate\FortiOS\ObjectSerializer;

/**
 * SwitchControllerManagedSwitchSwitchIdStpSettings Class Doc Comment
 *
 * @category Class
 * @package  Fortigate\FortiOS
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class SwitchControllerManagedSwitchSwitchIdStpSettings implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = '_switch_controller_managed_switch__switch_id__stp_settings';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'local_override' => 'string',
        'name' => 'string',
        'revision' => 'int',
        'hello_time' => 'int',
        'forward_time' => 'int',
        'max_age' => 'int',
        'max_hops' => 'int',
        'pending_timer' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'local_override' => null,
        'name' => null,
        'revision' => null,
        'hello_time' => null,
        'forward_time' => null,
        'max_age' => null,
        'max_hops' => null,
        'pending_timer' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'local_override' => 'local-override',
        'name' => 'name',
        'revision' => 'revision',
        'hello_time' => 'hello-time',
        'forward_time' => 'forward-time',
        'max_age' => 'max-age',
        'max_hops' => 'max-hops',
        'pending_timer' => 'pending-timer'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'local_override' => 'setLocalOverride',
        'name' => 'setName',
        'revision' => 'setRevision',
        'hello_time' => 'setHelloTime',
        'forward_time' => 'setForwardTime',
        'max_age' => 'setMaxAge',
        'max_hops' => 'setMaxHops',
        'pending_timer' => 'setPendingTimer'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'local_override' => 'getLocalOverride',
        'name' => 'getName',
        'revision' => 'getRevision',
        'hello_time' => 'getHelloTime',
        'forward_time' => 'getForwardTime',
        'max_age' => 'getMaxAge',
        'max_hops' => 'getMaxHops',
        'pending_timer' => 'getPendingTimer'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const LOCAL_OVERRIDE_ENABLE = 'enable';
    const LOCAL_OVERRIDE_DISABLE = 'disable';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getLocalOverrideAllowableValues()
    {
        return [
            self::LOCAL_OVERRIDE_ENABLE,
            self::LOCAL_OVERRIDE_DISABLE,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['local_override'] = $data['local_override'] ?? null;
        $this->container['name'] = $data['name'] ?? null;
        $this->container['revision'] = $data['revision'] ?? null;
        $this->container['hello_time'] = $data['hello_time'] ?? null;
        $this->container['forward_time'] = $data['forward_time'] ?? null;
        $this->container['max_age'] = $data['max_age'] ?? null;
        $this->container['max_hops'] = $data['max_hops'] ?? null;
        $this->container['pending_timer'] = $data['pending_timer'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getLocalOverrideAllowableValues();
        if (!is_null($this->container['local_override']) && !in_array($this->container['local_override'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'local_override', must be one of '%s'",
                $this->container['local_override'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['name']) && (mb_strlen($this->container['name']) > 31)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 31.";
        }

        if (!is_null($this->container['revision']) && ($this->container['revision'] > 65535)) {
            $invalidProperties[] = "invalid value for 'revision', must be smaller than or equal to 65535.";
        }

        if (!is_null($this->container['revision']) && ($this->container['revision'] < 0)) {
            $invalidProperties[] = "invalid value for 'revision', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['hello_time']) && ($this->container['hello_time'] > 10)) {
            $invalidProperties[] = "invalid value for 'hello_time', must be smaller than or equal to 10.";
        }

        if (!is_null($this->container['hello_time']) && ($this->container['hello_time'] < 1)) {
            $invalidProperties[] = "invalid value for 'hello_time', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['forward_time']) && ($this->container['forward_time'] > 30)) {
            $invalidProperties[] = "invalid value for 'forward_time', must be smaller than or equal to 30.";
        }

        if (!is_null($this->container['forward_time']) && ($this->container['forward_time'] < 4)) {
            $invalidProperties[] = "invalid value for 'forward_time', must be bigger than or equal to 4.";
        }

        if (!is_null($this->container['max_age']) && ($this->container['max_age'] > 40)) {
            $invalidProperties[] = "invalid value for 'max_age', must be smaller than or equal to 40.";
        }

        if (!is_null($this->container['max_age']) && ($this->container['max_age'] < 6)) {
            $invalidProperties[] = "invalid value for 'max_age', must be bigger than or equal to 6.";
        }

        if (!is_null($this->container['max_hops']) && ($this->container['max_hops'] > 40)) {
            $invalidProperties[] = "invalid value for 'max_hops', must be smaller than or equal to 40.";
        }

        if (!is_null($this->container['max_hops']) && ($this->container['max_hops'] < 1)) {
            $invalidProperties[] = "invalid value for 'max_hops', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['pending_timer']) && ($this->container['pending_timer'] > 15)) {
            $invalidProperties[] = "invalid value for 'pending_timer', must be smaller than or equal to 15.";
        }

        if (!is_null($this->container['pending_timer']) && ($this->container['pending_timer'] < 1)) {
            $invalidProperties[] = "invalid value for 'pending_timer', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets local_override
     *
     * @return string|null
     */
    public function getLocalOverride()
    {
        return $this->container['local_override'];
    }

    /**
     * Sets local_override
     *
     * @param string|null $local_override Enable to configure local STP settings that override global STP settings.    enable:Override global STP settings.    disable:Use global STP settings.
     *
     * @return self
     */
    public function setLocalOverride($local_override)
    {
        $allowedValues = $this->getLocalOverrideAllowableValues();
        if (!is_null($local_override) && !in_array($local_override, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'local_override', must be one of '%s'",
                    $local_override,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['local_override'] = $local_override;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name Name of local STP settings configuration.
     *
     * @return self
     */
    public function setName($name)
    {
        if (!is_null($name) && (mb_strlen($name) > 31)) {
            throw new \InvalidArgumentException('invalid length for $name when calling SwitchControllerManagedSwitchSwitchIdStpSettings., must be smaller than or equal to 31.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets revision
     *
     * @return int|null
     */
    public function getRevision()
    {
        return $this->container['revision'];
    }

    /**
     * Sets revision
     *
     * @param int|null $revision STP revision number (0 - 65535).
     *
     * @return self
     */
    public function setRevision($revision)
    {

        if (!is_null($revision) && ($revision > 65535)) {
            throw new \InvalidArgumentException('invalid value for $revision when calling SwitchControllerManagedSwitchSwitchIdStpSettings., must be smaller than or equal to 65535.');
        }
        if (!is_null($revision) && ($revision < 0)) {
            throw new \InvalidArgumentException('invalid value for $revision when calling SwitchControllerManagedSwitchSwitchIdStpSettings., must be bigger than or equal to 0.');
        }

        $this->container['revision'] = $revision;

        return $this;
    }

    /**
     * Gets hello_time
     *
     * @return int|null
     */
    public function getHelloTime()
    {
        return $this->container['hello_time'];
    }

    /**
     * Sets hello_time
     *
     * @param int|null $hello_time Period of time between successive STP frame Bridge Protocol Data Units (BPDUs) sent on a port (1 - 10 sec, default = 2).
     *
     * @return self
     */
    public function setHelloTime($hello_time)
    {

        if (!is_null($hello_time) && ($hello_time > 10)) {
            throw new \InvalidArgumentException('invalid value for $hello_time when calling SwitchControllerManagedSwitchSwitchIdStpSettings., must be smaller than or equal to 10.');
        }
        if (!is_null($hello_time) && ($hello_time < 1)) {
            throw new \InvalidArgumentException('invalid value for $hello_time when calling SwitchControllerManagedSwitchSwitchIdStpSettings., must be bigger than or equal to 1.');
        }

        $this->container['hello_time'] = $hello_time;

        return $this;
    }

    /**
     * Gets forward_time
     *
     * @return int|null
     */
    public function getForwardTime()
    {
        return $this->container['forward_time'];
    }

    /**
     * Sets forward_time
     *
     * @param int|null $forward_time Period of time a port is in listening and learning state (4 - 30 sec, default = 15).
     *
     * @return self
     */
    public function setForwardTime($forward_time)
    {

        if (!is_null($forward_time) && ($forward_time > 30)) {
            throw new \InvalidArgumentException('invalid value for $forward_time when calling SwitchControllerManagedSwitchSwitchIdStpSettings., must be smaller than or equal to 30.');
        }
        if (!is_null($forward_time) && ($forward_time < 4)) {
            throw new \InvalidArgumentException('invalid value for $forward_time when calling SwitchControllerManagedSwitchSwitchIdStpSettings., must be bigger than or equal to 4.');
        }

        $this->container['forward_time'] = $forward_time;

        return $this;
    }

    /**
     * Gets max_age
     *
     * @return int|null
     */
    public function getMaxAge()
    {
        return $this->container['max_age'];
    }

    /**
     * Sets max_age
     *
     * @param int|null $max_age Maximum time before a bridge port saves its configuration BPDU information (6 - 40 sec, default = 20).
     *
     * @return self
     */
    public function setMaxAge($max_age)
    {

        if (!is_null($max_age) && ($max_age > 40)) {
            throw new \InvalidArgumentException('invalid value for $max_age when calling SwitchControllerManagedSwitchSwitchIdStpSettings., must be smaller than or equal to 40.');
        }
        if (!is_null($max_age) && ($max_age < 6)) {
            throw new \InvalidArgumentException('invalid value for $max_age when calling SwitchControllerManagedSwitchSwitchIdStpSettings., must be bigger than or equal to 6.');
        }

        $this->container['max_age'] = $max_age;

        return $this;
    }

    /**
     * Gets max_hops
     *
     * @return int|null
     */
    public function getMaxHops()
    {
        return $this->container['max_hops'];
    }

    /**
     * Sets max_hops
     *
     * @param int|null $max_hops Maximum number of hops between the root bridge and the furthest bridge (1- 40, default = 20).
     *
     * @return self
     */
    public function setMaxHops($max_hops)
    {

        if (!is_null($max_hops) && ($max_hops > 40)) {
            throw new \InvalidArgumentException('invalid value for $max_hops when calling SwitchControllerManagedSwitchSwitchIdStpSettings., must be smaller than or equal to 40.');
        }
        if (!is_null($max_hops) && ($max_hops < 1)) {
            throw new \InvalidArgumentException('invalid value for $max_hops when calling SwitchControllerManagedSwitchSwitchIdStpSettings., must be bigger than or equal to 1.');
        }

        $this->container['max_hops'] = $max_hops;

        return $this;
    }

    /**
     * Gets pending_timer
     *
     * @return int|null
     */
    public function getPendingTimer()
    {
        return $this->container['pending_timer'];
    }

    /**
     * Sets pending_timer
     *
     * @param int|null $pending_timer Pending time (1 - 15 sec, default = 4).
     *
     * @return self
     */
    public function setPendingTimer($pending_timer)
    {

        if (!is_null($pending_timer) && ($pending_timer > 15)) {
            throw new \InvalidArgumentException('invalid value for $pending_timer when calling SwitchControllerManagedSwitchSwitchIdStpSettings., must be smaller than or equal to 15.');
        }
        if (!is_null($pending_timer) && ($pending_timer < 1)) {
            throw new \InvalidArgumentException('invalid value for $pending_timer when calling SwitchControllerManagedSwitchSwitchIdStpSettings., must be bigger than or equal to 1.');
        }

        $this->container['pending_timer'] = $pending_timer;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


