<?php
/**
 * SystemAccprofileNameNetgrpPermission
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Fortigate\FortiOS
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FortiOS CMDB
 *
 * REST API for configuring FortiOS objects and settings
 *
 * The version of the OpenAPI document: v2
 * Contact: fosguiqateam@fortinet.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Fortigate\FortiOS\Model\CMDB;

use \ArrayAccess;
use \Fortigate\FortiOS\ObjectSerializer;

/**
 * SystemAccprofileNameNetgrpPermission Class Doc Comment
 *
 * @category Class
 * @package  Fortigate\FortiOS
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class SystemAccprofileNameNetgrpPermission implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = '_system_accprofile__name__netgrp_permission';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'cfg' => 'string',
        'packet_capture' => 'string',
        'route_cfg' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'cfg' => null,
        'packet_capture' => null,
        'route_cfg' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'cfg' => 'cfg',
        'packet_capture' => 'packet-capture',
        'route_cfg' => 'route-cfg'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'cfg' => 'setCfg',
        'packet_capture' => 'setPacketCapture',
        'route_cfg' => 'setRouteCfg'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'cfg' => 'getCfg',
        'packet_capture' => 'getPacketCapture',
        'route_cfg' => 'getRouteCfg'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const CFG_NONE = 'none';
    const CFG_READ = 'read';
    const CFG_READ_WRITE = 'read-write';
    const PACKET_CAPTURE_NONE = 'none';
    const PACKET_CAPTURE_READ = 'read';
    const PACKET_CAPTURE_READ_WRITE = 'read-write';
    const ROUTE_CFG_NONE = 'none';
    const ROUTE_CFG_READ = 'read';
    const ROUTE_CFG_READ_WRITE = 'read-write';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCfgAllowableValues()
    {
        return [
            self::CFG_NONE,
            self::CFG_READ,
            self::CFG_READ_WRITE,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPacketCaptureAllowableValues()
    {
        return [
            self::PACKET_CAPTURE_NONE,
            self::PACKET_CAPTURE_READ,
            self::PACKET_CAPTURE_READ_WRITE,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRouteCfgAllowableValues()
    {
        return [
            self::ROUTE_CFG_NONE,
            self::ROUTE_CFG_READ,
            self::ROUTE_CFG_READ_WRITE,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['cfg'] = $data['cfg'] ?? null;
        $this->container['packet_capture'] = $data['packet_capture'] ?? null;
        $this->container['route_cfg'] = $data['route_cfg'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getCfgAllowableValues();
        if (!is_null($this->container['cfg']) && !in_array($this->container['cfg'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'cfg', must be one of '%s'",
                $this->container['cfg'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getPacketCaptureAllowableValues();
        if (!is_null($this->container['packet_capture']) && !in_array($this->container['packet_capture'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'packet_capture', must be one of '%s'",
                $this->container['packet_capture'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getRouteCfgAllowableValues();
        if (!is_null($this->container['route_cfg']) && !in_array($this->container['route_cfg'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'route_cfg', must be one of '%s'",
                $this->container['route_cfg'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets cfg
     *
     * @return string|null
     */
    public function getCfg()
    {
        return $this->container['cfg'];
    }

    /**
     * Sets cfg
     *
     * @param string|null $cfg Network Configuration.    none:No access.    read:Read access.    read-write:Read/write access.
     *
     * @return self
     */
    public function setCfg($cfg)
    {
        $allowedValues = $this->getCfgAllowableValues();
        if (!is_null($cfg) && !in_array($cfg, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'cfg', must be one of '%s'",
                    $cfg,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['cfg'] = $cfg;

        return $this;
    }

    /**
     * Gets packet_capture
     *
     * @return string|null
     */
    public function getPacketCapture()
    {
        return $this->container['packet_capture'];
    }

    /**
     * Sets packet_capture
     *
     * @param string|null $packet_capture Packet Capture Configuration.    none:No access.    read:Read access.    read-write:Read/write access.
     *
     * @return self
     */
    public function setPacketCapture($packet_capture)
    {
        $allowedValues = $this->getPacketCaptureAllowableValues();
        if (!is_null($packet_capture) && !in_array($packet_capture, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'packet_capture', must be one of '%s'",
                    $packet_capture,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['packet_capture'] = $packet_capture;

        return $this;
    }

    /**
     * Gets route_cfg
     *
     * @return string|null
     */
    public function getRouteCfg()
    {
        return $this->container['route_cfg'];
    }

    /**
     * Sets route_cfg
     *
     * @param string|null $route_cfg Router Configuration.    none:No access.    read:Read access.    read-write:Read/write access.
     *
     * @return self
     */
    public function setRouteCfg($route_cfg)
    {
        $allowedValues = $this->getRouteCfgAllowableValues();
        if (!is_null($route_cfg) && !in_array($route_cfg, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'route_cfg', must be one of '%s'",
                    $route_cfg,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['route_cfg'] = $route_cfg;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


